### ISSUE TITLE
Allow to configure deploymentscripts.createdata.type depending on SystemSetup.Process

### ISSUE THREAD

**Issue by eBusEntwHOFM** [arobirosa/areco-deployment-script-manager#13]
Would be awesome to be able to configure `deploymentscripts.createdata.type` depending on the system setup process type. That will give more flexibility and allow to bypass differend dependency scenarios.

For example, an Areco deployment script can depend on a sample data, which has been imported while `initialize`, but not while `updatesystem`. In that case `deploymentscripts.createdata.type=ESSENTIAL` will cause the script to fail while `init` (because it depends on sample data, which has been imported while `PROJECT` step), and `deploymentscripts.createdata.type=PROJECT` will skip Areco scripts execution while `ant updatesystem` at all.

**Comment by eBusEntwHOFM** [comment]
PR will follow.

**Comment by arobirosa** [comment]
Hi (sorry but I don't your name),

Thanks a lot for proposing changes to the deployment manager.

**I don't recommend using sample or project data once all the impex scripts where migrated** to Areco deployment scripts. [Here you will find the instructuions for the migration](https://github.com/arobirosa/areco-deployment-script-manager/wiki/Installation#migration-of-the-hybris-create-project-and-essential-data-scripts)

**The creation of sample data or project data has shortcomings** which the deployment managers avoids. For example, the creation can be turned off and there isn't any error handling of impex errors (you have to check the console output) which may lead to different environmet with different data samples. This makes troubleshooting harder.

If you can't migrated all your current sample and project data scripts to Areco deployment scripts, please help me understand what problem you currently have and I will try to come up with a solution. **If you can't migrate the sample and project data scripts, please tell me why.**

Regards,

Antonio

**Comment by arobirosa** [comment]
Hi @eBusEntwHOFM ,

do you have any update on this issue? I am planning to change the areco deployment manager to avoid the need to migrate old project or essential data impexes. Deployment Scripts will only be run in the last custom extension.

Cheers!

**Comment by arobirosa** [comment]
The FAQ was updated explaining [why the usage of sample or project data step for the arecos is not recommeded.](https://github.com/arobirosa/areco-deployment-script-manager/wiki/FAQ#my-deployment-scripts-depend-on-sample-data-how-can-i-turn-off-the-execution-of-these-scripts-if-there-is-no-sample-data).

Unfortunately I couldn't not understand the issues faced in your project, @eBusEntwHOFM 

I close this ticket. No changes were done.
