### ISSUE TITLE
Measure Coverage with JaCoCo

### ISSUE THREAD

**Issue by arobirosa** [arobirosa/areco-deployment-script-manager#2]
### Steps to reproduce:
 * Checkout repository
* Run **ant clean all yunitinit qa**

### Expected Result
ca. 75% Coverage

### Actual Result
100% coverage and no classes are shown

### Log Entries: None

**Comment by arobirosa** [comment]
Cobertura isn't compatible with Java 11 because it uses ASM 5. The project is abandoned. I will migrate the coverage analysis to [JaCoCo](https://en.wikipedia.org/wiki/Java_code_coverage_tools) which is compatible with Java 11 and used by SonarCube.

**Comment by arobirosa** [comment]
Sonarcloud don't have a free plan for open-source projects and I don't have a server to host a sonarqube.

**Comment by fibsifan** [comment]
Hi Antonio,

I use a free Sonarcloud account for a project on gitlab, I think it is still possible to register your project as open source.

As for analyzing sap commerce extensions with Jacoco: that seems to be a bit tricky, but not impossible. Do you use GitHub actions to run tests on pull requests?

**Comment by arobirosa** [comment]
Hi @fibsifan ,

I just created a free account in sonarcloud and I will try to try the tests and get the metrics from this project there.

Thanks a lot, Johannes!

**Comment by arobirosa** [comment]
Now the ant target qa checks the test line coverage with JaCoCo. If an unit or integration tests fails or the line coverage is lower than 75%, the build fails.

In the ticket #10 I will integrate sonarqube and adapt the ant target qa to send the coverage information to sonar.

I close this ticket.
