### ISSUE TITLE
Show areco scripts which are pending execution

### ISSUE THREAD

**Issue by arobirosa** [arobirosa/areco-deployment-script-manager#23]
**Is your feature request related to a problem?**

If a areco script has an error, the programmers don't know what arecos coming after that one weren't executed.

**Describe the solution you'd like**

All arecos which will be executed after the error is solved are stored with the status 'PENDING'.

**Describe alternatives you've considered**

To show the list of pending arecos in a log message. 

**Additional context**
Mone

**Comment by DevPJ9** [comment]
Hello @arobirosa I would like to work on this.

**Comment by DevPJ9** [comment]
Hello @arobirosa. Thanks for considering my request. 

No, I am a bit confused about the requirement , do we have to assign pending arecos "PENDING" status or we just have to log it? I would appreciate some guidance during the implementation of this. 

I am not sure about SAP commerce version, not worked with it.

No special permissons are needed as of now, we can discuss it later depending on the requirements as we discuss the solution.

Thanks.

**Comment by arobirosa** [comment]
Hi @DevPJ9 ,

I will upgrade the project to SAP commerce 2205.

I believe that a solution could be that DeploymentScriptFinder creates new script executions with status PENDING (new status). Then DeploymentScriptRunner takes these script executions and runs them. If the directory with the areco was removed from disk, the execution script is saved with the status REMOVED_ON_DISK (new status).

Please check if this solution is possible.

Cheers!

**Comment by DevPJ9** [comment]
ok, sure. I will look into it and let you if I get stuck.

**Comment by arobirosa** [comment]
The solution is more complex than what I thought. This ticket is not suitable for contributors.

**Comment by arobirosa** [comment]
This change solves an issue when running arecos which remove CMSComponents: The method de.hybris.platform.cms2.servicelayer.interceptor.impl.CMSAbstractComponentRemoveInterceptor#onRemove try to save all models including the script execution models which are just created. This makes the areco fail.

If the script execution models are saved by the runner with the status *pending*, this bug is solved.

**Comment by arobirosa** [comment]
Hi @DevPJ9, 

Because this ticket solves a bug found on Friday, I want to ask you if I can start working on it on Friday.

Thanks a lot!

**Comment by DevPJ9** [comment]
Hello @arobirosa. Yes, As you mentioned it requires a good knowledge of SAP technologies and I am working on windows not Linux as well so I think I will not be able to contribute to this task.

**Comment by arobirosa** [comment]
Hi @DevPJ9 ,

I will assign this ticket to me.

Under Windows isn't possible to develop with SAP commerce because the path of some files is too long. You must use a VM with linux or a machine with MacOS.

Thanks a lot!

**Comment by arobirosa** [comment]
I commited and reverted an integration test to try to reproduce the error with the CMSAbstractComponentRemoveInterceptor. It was not possible.

I will continue with the implementation of this ticket.

**Comment by arobirosa** [comment]
Now the deployment scripts which weren't executed because one failed which **are in the same hybris extension** are shown in backoffice.  The deployment manager won't generate the "pending" executions across all extensions because this requires a big refactoring of the script runner and most of the projects only have one extension with deployment scripts.

[This technical limitation was documented here](/arobirosa/areco-deployment-script-manager/wiki/Limitations)
